### PR TITLE
Disable `linebreaks` and `no-empty-first-line` and `unicode-bom` three rules

### LINKED ISSUE #40: Add `linebreaks` and `no-empty-first-line` and `unicode-bom`  three rules
These three rules have been covered by `Prettier`, they should be added to this config.

### PR DESCRIPTION
**Pull request by yangmingshan**
Fixes #40

### CODE REVIEW

**Comment by shannonmoeller** [comment]
Thanks for the PR!

**Comment by shannonmoeller** [comment]
Released as v8.

**Comment by HaoChuan9421** [comment]
Why disable "unicode-bom"? you published this change even if the rule didn't pass the test!
image
image

**Comment by shannonmoeller** [comment]
@HaoChuan9421 The tests passed after yangmingshan upgraded the minimum required version of stylelint to 11.0.0:

image

This was a breaking change which is why I released it as 8.0.0. You may need to delete your `node_modules` directory and the lock file (`package-lock.json` or `yarn.lock`) and reinstall.

**Comment by shannonmoeller** [comment]
Also, the rule was disabled because `prettier` always removes the BOM.

https://github.com/prettier/prettier/pull/2373

**Comment by HaoChuan9421** [comment]
@shannonmoeller Sorry, It works fine. The error above is caused by the VSCode extentsion [vscode-stylelint](https://github.com/stylelint/vscode-stylelint). It use built in stylelint which version is 10.  https://github.com/stylelint/vscode-stylelint/issues/4. Thanks a lot!

**Pull request merged**
